---
- name: Deploy PostgreSQL and SonarQube for code analysis
  hosts: all
  become: yes
  tasks:
    - name: Install Docker prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - python3-pip

    - name: Install Docker Python module
      pip:
        name: docker
        executable: pip3

    - name: Create Docker network
      docker_network:
        name: sonarqube-network
        state: present

    - name: Pull PostgreSQL Docker image
      docker_image:
        name: postgres:13
        source: pull

    - name: Run PostgreSQL container
      docker_container:
        name: postgres-sonarqube
        image: postgres:13
        state: started
        restart_policy: always
        networks:
          - name: sonarqube-network
        env:
          POSTGRES_USER: sonar
          POSTGRES_PASSWORD: sonar123
          POSTGRES_DB: sonarqube
        ports:
          - "5432:5432"

    - name: Pull SonarQube Docker image
      docker_image:
        name: sonarqube:10.4.1-community
        source: pull

    - name: Run SonarQube container
      docker_container:
        name: sonarqube
        image: sonarqube:10.4.1-community
        state: started
        restart_policy: always
        networks:
          - name: sonarqube-network
        memory: 2g
        env:
          SONAR_JDBC_URL: jdbc:postgresql://postgres-sonarqube:5432/sonarqube
          SONAR_JDBC_USERNAME: sonar
          SONAR_JDBC_PASSWORD: sonar123
        ports:
          - "9000:9000"
